bind 0.0.0.0
port 6379
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
user default off -@all
user admin on >myStrongPassword ~* +@all
user user_social_media on >socialpassword ~posts:* ~likes:* ~follow:* ~commentary:* +GET +MGET +EXISTS +SET +DEL +INCR +PUBLISH +SUBSCRIBE
user activity_sensor_cache on >sensorpassword ~activity_id:* +GET +MGET +SET +DEL
user worker on >workerpassword allkeys allcommands