services:
  grafana:
    build: 
        context: ./grafana
    container_name: grafana-dashboard-sensor-monitoring
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboard/:/etc/grafana/provisioning/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin



  marimo:
    build:
      context: ./marimo-dev
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: marimo-dev
    command: marimo edit --no-token --host 0.0.0.0 -p 8080
    env_file:
      - .env
    volumes:
      - ./marimo-dev/scripts:/code/scripts
    working_dir: /code
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true

  postgres:
    build: 
      context: ./postgresql
    container_name: postgres_social_media
    environment:
      POSTGRES_DB: social_media_sports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5532:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/scripts/initdb/:/docker-entrypoint-initdb.d/
      - ./postgresql/scripts/inserts/:/inserts/
      - ./postgresql/scripts/config/:/etc/postgresql/
  redis:
    build: 
      context: ./redis
    container_name: redis_social_media
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data/:/test_data/
      - ./redis/backup/data/:/data/

  influxdb:
    build: ./influxdb
    container_name: influxdb_sensors_activity
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/sensor:/data/sensor
      - ./influxdb/monitoring:/data/monitoring
      - ./influxdb/config/config.toml:/etc/influxdb/config.toml
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: sports_org
      DOCKER_INFLUXDB_INIT_RETENTION: 168h 
      DOCKER_INFLUXDB_INIT_BUCKET: sports_metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-token

  python:
    build:
      context: ./python-dev
    container_name: python-dev
    command: 
    env_file:
      - .env
    volumes:
      - ./python-dev/scripts:/code
    working_dir: /code
    stdin_open: true
    tty: true

  postgres-backup:
    image: postgres:16
    depends_on:
      - postgres
    volumes:
      - ./postgresql/scripts/backup/data/:/backup/
      - ./postgresql/scripts/backup/backup.sh:/backup.sh
    environment:
      PGPASSWORD: postgres
    entrypoint: ["bash", "./backup.sh"]

  redis-backup:
    image: redis:7
    depends_on:
      - redis
    volumes:
      - ./redis/backup/data/:/backup_data/
      - ./redis/backup/backup.sh:/backup.sh

    command: ["bash", "../backup.sh"]

  influx-backup:
    image: influxdb:2.7
    depends_on:
      - influxdb
    volumes:
      - ./influxdb/backup/influx:/backup
      - ./influxdb/backup/backup.sh:/backup.sh
    environment:
      INFLUX_TOKEN: my-super-token
    entrypoint: ["bash", "./backup.sh"]

  grafana-backup:
    image: alpine
    container_name: grafana-backup
    depends_on:
      - grafana
    volumes:
    - ./grafana/grafana-data:/var/lib/grafana
    - ./grafana/backup/data:/backup
    - ./grafana/backup/backup.sh:/backup.sh
    entrypoint: ["sh", "/backup.sh"]

volumes:
  postgres_data:
  redis_data:
  influxdb_data:
  grafana-data: